### ISSUE TITLE
Fails to build on OS X 10.11.6

### ISSUE THREAD

**Issue by leonklingele** [git-lfs/git-lfs#3999]
`<sys/clonefile.h>` should only be included if it's supported: https://github.com/git-lfs/git-lfs/blob/7237dd0fed199ab60331fd4fefe5dcd4be4ad18a/tools/util_darwin.go#L21

Build log:

```sh
$ brew install git-lfs
==> Downloading https://github.com/git-lfs/git-lfs/releases/download/v2.10.0/git-lfs-v2.10.0.tar.gz
==> gem install ronn
==> make vendor
==> make
Last 15 lines from /Users/user/Library/Logs/Homebrew/git-lfs/03.make:
go: finding gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: finding github.com/davecgh/go-spew v1.1.1
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding golang.org/x/text v0.3.0
go: finding golang.org/x/crypto v0.0.0-20190426145343-a29dc8fdc734
go: finding gopkg.in/jcmturner/aescts.v1 v1.0.1
go: finding gopkg.in/jcmturner/rpc.v0 v0.0.2
git-lfs: skipping fmt, no goimports found at `goimports` ...
GOOS= GOARCH= go build -ldflags=" -X github.com/git-lfs/git-lfs/config.GitCommit= -s -w " -gcflags="all=-trimpath="$HOME" " -asmflags="all=-trimpath="$HOME"" -trimpath -o ./bin/git-lfs ./git-lfs.go
# github.com/git-lfs/git-lfs/tools
tools/util_darwin.go:21:10: fatal error: 'sys/clonefile.h' file not found
#include <sys/clonefile.h>
         ^
1 error generated.
make: *** [bin/git-lfs] Error 2
```

**Comment by bk2204** [comment]
Hey,

Thanks for writing in.  I don't think there's a way in Go for us to conditionally build files based on the version of the OS.  Even if we could conditionally include the header, we'd still fail to link because this file uses the function call.  And since macOS 10.11 is no longer supported, so we couldn't possibly test this case.

However, if you're building on an older version of macOS, you can try to build with the `CGO_ENABLED=0` flag and then this file won't be compiled in, and a stub implementation will be used instead.

Having said that, if you can come up with a way to make this work out of the box without impacting newer systems negatively, we're happy to accept a PR to do so.
