### PR TITLE
Cygwin tools

### PR DESCRIPTION
**Pull request by ttaylorr**
This pull-request expands on #1820 by spiking out some functions in the `tools` package to convert Windows paths to Cygwin paths. 

This was prompted by https://github.com/git-lfs/git-lfs/issues/865#issuecomment-281044331, which was comparing the Windows path from `os.Getwd()` with the Git working dir in Cygwin format from `config.LocalWorkingDir`.

Since we don't have integration tests on Cygwin (though we should look into that) I'm leaving this as a [WIP] until we can verify that it works as expected.

### CODE REVIEW

**Comment by ttaylorr** [comment]
As a side note, I'm 👍 that we can skip shelling out on non-Windows platforms, but 👎 on the `tools.ConvertIfCygwin`. I think that function is a _bit_ too magical.

**Comment by ttaylorr** [comment]
> Since we don't have integration tests on Cygwin (though we should look into that)

@sschuberth do you have any thoughts about running integration tests on Cygwin using AppVeyor?

**Comment by sschuberth** [comment]
@ttaylorr I'll come up with something.

**Comment by sschuberth** [comment]
@ttaylorr I've added a few commits on top of you branch in my [cygwin-tools-appveyor](https://github.com/git-lfs/git-lfs/compare/cygwin-tools...cygwin-tools-appveyor) branch. You can see the matrix build [here](https://ci.appveyor.com/project/git-lfs/git-lfs/build/1.0.1433), and also see here that [the Cygwin build still fails](https://ci.appveyor.com/project/git-lfs/git-lfs/build/1.0.1433/job/anwfuyfxegue3j8g) with errors like:

    --- FAIL: TestCurrentRefAndCurrentRemoteRef (3.39s)
        testutils.go:186: Error running git command 'git push -u origin master:someremotebranch': exit status 128 ssh: Could not resolve hostname c: Name or service not known
            fatal: Could not read from remote repository.
            
            Please make sure you have the correct access rights
            and the repository exists.

Feel free to cherry-pick / merge my changes as you see fit.

**Comment by ttaylorr** [comment]
> Feel free to cherry-pick / merge my changes as you see fit.

Thanks for taking a look at this and getting things going on AppVeyor. I went ahead and merged your branch into mine.

I'm seeing a few common failures on the Cygwin builds, so I'm going to leave those here to track:

- [ ] `git.GetTrackedFiles` doesn't return results outside of the root directory.
- [ ] `testutils.RunGitCommand` fails, not sure why

Those are the ones that I've been able to see so far in the Go tests. I don't quite have the time to look at those right now, but if someone else wants to, I'd much appreciate it ✨ .

**Comment by sschuberth** [comment]
> I went ahead and merged your branch into mine.

I don't see the changes from my cygwin-tools-appveyor branch in there anymore. Where did they go?

**Comment by ttaylorr** [comment]
@sschuberth, I backed out of those since they were causing the build to fail. After 2.0.0, I'd like to bring those changes back in and legitimately fix the problems on Cygwin.

**Comment by sschuberth** [comment]
@ttaylorr I would have been nice if you told me before, as I had deleted my local branch already, since you said to have merged it. Anyway, I was able to restore it via `git reflog`, and have pushed it again.

**Comment by erebel55** [comment]
This works great, thank you! 💃
